
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
  Documentation:
    Enabled: false
  TargetRubyVersion: 2.6.5

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
